namespace PROG7312POETask2
{
    partial class frmAddEvent
    {
        /// <summary>
        /// Required designer variable to manage UI components.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// This is required by the Designer when disposing resources.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose(); // Dispose of the components
            }
            base.Dispose(disposing); // Call base class dispose method
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Initialize and set up the components required for the form UI.
        /// This method is automatically generated by the designer and should not be manually modified.
        /// </summary>
        private void InitializeComponent()
        {
            // Initialize form controls (labels, textboxes, buttons, etc.)
            this.label1 = new System.Windows.Forms.Label();
            this.txtEventName = new System.Windows.Forms.TextBox();
            this.cmbCategory = new System.Windows.Forms.ComboBox();
            this.label2 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.dtpEventDateTime = new System.Windows.Forms.DateTimePicker();
            this.btnCancel = new System.Windows.Forms.Button();
            this.btnSave = new System.Windows.Forms.Button();
            this.btnClearform = new System.Windows.Forms.Button();
            this.SuspendLayout();
            // 
            // label1
            // Label to display "Event Name"
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.ForeColor = System.Drawing.SystemColors.Control;
            this.label1.Location = new System.Drawing.Point(64, 73);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(100, 20);
            this.label1.TabIndex = 0;
            this.label1.Text = "Event Name";
            // 
            // txtEventName
            // Textbox for entering event name
            this.txtEventName.Location = new System.Drawing.Point(242, 71);
            this.txtEventName.Name = "txtEventName";
            this.txtEventName.Size = new System.Drawing.Size(190, 22);
            this.txtEventName.TabIndex = 1;
            // 
            // cmbCategory
            // ComboBox to select event category
            this.cmbCategory.FormattingEnabled = true;
            this.cmbCategory.Location = new System.Drawing.Point(242, 156);
            this.cmbCategory.Name = "cmbCategory";
            this.cmbCategory.Size = new System.Drawing.Size(200, 24);
            this.cmbCategory.TabIndex = 2;
            // 
            // label2
            // Label to display "Category"
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.ForeColor = System.Drawing.SystemColors.Control;
            this.label2.Location = new System.Drawing.Point(64, 156);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(76, 20);
            this.label2.TabIndex = 3;
            this.label2.Text = "Category";
            // 
            // label3
            // Label to display "Event Date and Time"
            this.label3.AutoSize = true;
            this.label3.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.ForeColor = System.Drawing.SystemColors.Control;
            this.label3.Location = new System.Drawing.Point(64, 263);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(166, 20);
            this.label3.TabIndex = 4;
            this.label3.Text = "Event Date and Time";
            // 
            // dtpEventDateTime
            // DateTimePicker for selecting event date and time
            this.dtpEventDateTime.Location = new System.Drawing.Point(242, 261);
            this.dtpEventDateTime.Name = "dtpEventDateTime";
            this.dtpEventDateTime.Size = new System.Drawing.Size(200, 22);
            this.dtpEventDateTime.TabIndex = 5;
            // 
            // btnCancel
            // Button for canceling and closing the form
            this.btnCancel.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnCancel.Location = new System.Drawing.Point(455, 440);
            this.btnCancel.Name = "btnCancel";
            this.btnCancel.Size = new System.Drawing.Size(97, 35);
            this.btnCancel.TabIndex = 6;
            this.btnCancel.Text = "Cancel";
            this.btnCancel.UseVisualStyleBackColor = true;
            this.btnCancel.Click += new System.EventHandler(this.btnCancel_Click);
            // 
            // btnSave
            // Button for saving the event details
            this.btnSave.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnSave.Location = new System.Drawing.Point(192, 440);
            this.btnSave.Name = "btnSave";
            this.btnSave.Size = new System.Drawing.Size(87, 35);
            this.btnSave.TabIndex = 7;
            this.btnSave.Text = "Save";
            this.btnSave.UseVisualStyleBackColor = true;
            this.btnSave.Click += new System.EventHandler(this.btnSave_Click);
            // 
            // btnClearform
            // Button to clear the form inputs
            this.btnClearform.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnClearform.Location = new System.Drawing.Point(242, 332);
            this.btnClearform.Name = "btnClearform";
            this.btnClearform.Size = new System.Drawing.Size(101, 38);
            this.btnClearform.TabIndex = 9;
            this.btnClearform.Text = "Clear form";
            this.btnClearform.UseVisualStyleBackColor = true;
            this.btnClearform.Click += new System.EventHandler(this.btnClearform_Click);
            // 
            // frmAddEvent
            // Main form setup with styling, controls, and event handlers
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.SystemColors.HotTrack; // Set background color
            this.BackgroundImage = global::PROG7312POETask2.Properties.Resources.municipality; // Set background image
            this.ClientSize = new System.Drawing.Size(925, 550); // Set form size
            this.Controls.Add(this.btnClearform); // Add the Clear form button to the form
            this.Controls.Add(this.btnSave); // Add the Save button to the form
            this.Controls.Add(this.btnCancel); // Add the Cancel button to the form
            this.Controls.Add(this.dtpEventDateTime); // Add the DateTimePicker to the form
            this.Controls.Add(this.label3); // Add the Event Date and Time label to the form
            this.Controls.Add(this.label2); // Add the Category label to the form
            this.Controls.Add(this.cmbCategory); // Add the ComboBox for categories to the form
            this.Controls.Add(this.txtEventName); // Add the TextBox for event name to the form
            this.Controls.Add(this.label1); // Add the Event Name label to the form
            this.Name = "frmAddEvent"; // Set form name
            this.Text = "frmEvents"; // Set form title
            this.TopMost = true; // Keep the form on top
            this.Load += new System.EventHandler(this.frmAddEvent_Load); // Event handler for form load
            this.ResumeLayout(false);
            this.PerformLayout(); // Finalize the form setup
        }

        #endregion

        // Form controls declaration
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.TextBox txtEventName;
        private System.Windows.Forms.ComboBox cmbCategory;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.DateTimePicker dtpEventDateTime;
        private System.Windows.Forms.Button btnCancel;
        private System.Windows.Forms.Button btnSave;
        private System.Windows.Forms.Button btnClearform;
    }
}
