namespace PROG7312POETask2
{
    partial class frmLocalEventsandAnnouncements
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// This method contains the code generated by the Windows Form Designer.
        /// It defines the layout and properties of controls on the form.
        /// </summary>
        private void InitializeComponent()
        {
            // Label for Events title
            this.label1 = new System.Windows.Forms.Label();

            // Label for Announcements title
            this.label2 = new System.Windows.Forms.Label();

            // Textbox for searching events
            this.txtSearchEvent = new System.Windows.Forms.TextBox();

            // Button to trigger search functionality
            this.btnSearch = new System.Windows.Forms.Button();

            // Label for the Search prompt
            this.label3 = new System.Windows.Forms.Label();

            // Button to add a new event
            this.btnAddEvent = new System.Windows.Forms.Button();

            // Button to remove an existing event
            this.btnRemoveEvent = new System.Windows.Forms.Button();

            // Button to add a new announcement
            this.btnAddAnnouncements = new System.Windows.Forms.Button();

            // Button to remove an existing announcement
            this.btnRemoveAnnouncements = new System.Windows.Forms.Button();

            // ListView to display all the events
            this.lvEvents = new System.Windows.Forms.ListView();

            // ListBox to display all the announcements
            this.lbAnnouncements = new System.Windows.Forms.ListBox();

            // Label to show recommendations based on user searches
            this.lblRecommendation = new System.Windows.Forms.Label();

            // Method that initializes and lays out the form's controls
            this.SuspendLayout();
            // 
            // label1  Display the text 'Events' to label the events list
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.ForeColor = System.Drawing.SystemColors.Control;
            this.label1.Location = new System.Drawing.Point(45, 114);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(66, 20);
            this.label1.TabIndex = 0;
            this.label1.Text = "Events";
            // 
            // label2  Display the text 'Announcements' to label the announcements list
            // 
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.ForeColor = System.Drawing.SystemColors.Control;
            this.label2.Location = new System.Drawing.Point(694, 114);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(142, 20);
            this.label2.TabIndex = 1;
            this.label2.Text = "Announcements";
            // 
            // txtSearchEvent Allows user to enter search queries to find specific events
            // 
            this.txtSearchEvent.Location = new System.Drawing.Point(176, 22);
            this.txtSearchEvent.Name = "txtSearchEvent";
            this.txtSearchEvent.Size = new System.Drawing.Size(232, 22);
            this.txtSearchEvent.TabIndex = 3;
            // 
            // btnSearch Initiates search for events when clicked
            // 
            this.btnSearch.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnSearch.Location = new System.Drawing.Point(240, 66);
            this.btnSearch.Name = "btnSearch";
            this.btnSearch.Size = new System.Drawing.Size(105, 28);
            this.btnSearch.TabIndex = 4;
            this.btnSearch.Text = "Search";
            this.btnSearch.UseVisualStyleBackColor = true;
            this.btnSearch.Click += new System.EventHandler(this.btnSearch_Click);
            // 
            // label3  Prompts user to search for events
            // 
            this.label3.AutoSize = true;
            this.label3.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.ForeColor = System.Drawing.SystemColors.Control;
            this.label3.Location = new System.Drawing.Point(15, 22);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(155, 20);
            this.label3.TabIndex = 5;
            this.label3.Text = "Search for an event";
            // 
            // btnAddEvent  Allows user to add a new event to the list
            // 
            this.btnAddEvent.Location = new System.Drawing.Point(99, 580);
            this.btnAddEvent.Name = "btnAddEvent";
            this.btnAddEvent.Size = new System.Drawing.Size(96, 23);
            this.btnAddEvent.TabIndex = 6;
            this.btnAddEvent.Text = "Add Event";
            this.btnAddEvent.UseVisualStyleBackColor = true;
            this.btnAddEvent.Click += new System.EventHandler(this.btnAddEvent_Click);
            // 
            // btnRemoveEvent Allows user to remove a selected event
            // 
            this.btnRemoveEvent.Location = new System.Drawing.Point(276, 580);
            this.btnRemoveEvent.Name = "btnRemoveEvent";
            this.btnRemoveEvent.Size = new System.Drawing.Size(132, 23);
            this.btnRemoveEvent.TabIndex = 7;
            this.btnRemoveEvent.Text = "Remove Event";
            this.btnRemoveEvent.UseVisualStyleBackColor = true;
            this.btnRemoveEvent.Click += new System.EventHandler(this.btnRemoveEvent_Click);
            // 
            // btnAddAnnouncements  Allows user to add a new announcement
            // 
            this.btnAddAnnouncements.Location = new System.Drawing.Point(706, 571);
            this.btnAddAnnouncements.Name = "btnAddAnnouncements";
            this.btnAddAnnouncements.Size = new System.Drawing.Size(104, 41);
            this.btnAddAnnouncements.TabIndex = 9;
            this.btnAddAnnouncements.Text = "Add Announcements";
            this.btnAddAnnouncements.UseVisualStyleBackColor = true;
            this.btnAddAnnouncements.Click += new System.EventHandler(this.btnAddAnnouncements_Click);
            // 
            // btnRemoveAnnouncements Allows user to remove a selected announcement
            // 
            this.btnRemoveAnnouncements.Location = new System.Drawing.Point(874, 571);
            this.btnRemoveAnnouncements.Name = "btnRemoveAnnouncements";
            this.btnRemoveAnnouncements.Size = new System.Drawing.Size(84, 41);
            this.btnRemoveAnnouncements.TabIndex = 10;
            this.btnRemoveAnnouncements.Text = "Remove Announcements";
            this.btnRemoveAnnouncements.UseVisualStyleBackColor = true;
            this.btnRemoveAnnouncements.Click += new System.EventHandler(this.btnRemoveAnnouncements_Click);
            // 
            // lvEvents Displays the list of events
            // 
            this.lvEvents.HideSelection = false;
            this.lvEvents.Location = new System.Drawing.Point(39, 153);
            this.lvEvents.Name = "lvEvents";
            this.lvEvents.Size = new System.Drawing.Size(508, 403);
            this.lvEvents.TabIndex = 11;
            this.lvEvents.UseCompatibleStateImageBehavior = false;
            this.lvEvents.View = System.Windows.Forms.View.List;
            // 
            // lbAnnouncements Displays the list of announcements
            // 
            this.lbAnnouncements.FormattingEnabled = true;
            this.lbAnnouncements.ItemHeight = 16;
            this.lbAnnouncements.Location = new System.Drawing.Point(658, 153);
            this.lbAnnouncements.Name = "lbAnnouncements";
            this.lbAnnouncements.Size = new System.Drawing.Size(332, 404);
            this.lbAnnouncements.TabIndex = 8;
            // 
            // lblRecommendation Displays event recommendations based on search history
            // 
            this.lblRecommendation.AutoSize = true;
            this.lblRecommendation.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblRecommendation.ForeColor = System.Drawing.SystemColors.Control;
            this.lblRecommendation.Location = new System.Drawing.Point(217, 97);
            this.lblRecommendation.Name = "lblRecommendation";
            this.lblRecommendation.Size = new System.Drawing.Size(153, 20);
            this.lblRecommendation.TabIndex = 20;
            this.lblRecommendation.Text = "Recommendation";
            this.lblRecommendation.Click += new System.EventHandler(this.lblRecommendation_Click);
            // 
            // frmLocalEventsandAnnouncements
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.SystemColors.HotTrack;
            this.BackgroundImage = global::PROG7312POETask2.Properties.Resources.municipality;
            this.ClientSize = new System.Drawing.Size(1137, 676);
            this.Controls.Add(this.lblRecommendation);
            this.Controls.Add(this.lvEvents);
            this.Controls.Add(this.btnRemoveAnnouncements);
            this.Controls.Add(this.btnAddAnnouncements);
            this.Controls.Add(this.lbAnnouncements);
            this.Controls.Add(this.btnRemoveEvent);
            this.Controls.Add(this.btnAddEvent);
            this.Controls.Add(this.label3);
            this.Controls.Add(this.btnSearch);
            this.Controls.Add(this.txtSearchEvent);
            this.Controls.Add(this.label2);
            this.Controls.Add(this.label1);
            this.Name = "frmLocalEventsandAnnouncements";
            this.Text = "frmLocalEventsandAnnouncements";
            this.TopMost = true;
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.TextBox txtSearchEvent;
        private System.Windows.Forms.Button btnSearch;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Button btnAddEvent;
        private System.Windows.Forms.Button btnRemoveEvent;
        private System.Windows.Forms.Button btnAddAnnouncements;
        private System.Windows.Forms.Button btnRemoveAnnouncements;
        private System.Windows.Forms.ListView lvEvents;
        private System.Windows.Forms.ListBox lbAnnouncements;
        private System.Windows.Forms.Label lblRecommendation;
    }
}